judge_receiver:
  ros__parameters:
    judge_host: "127.0.0.1"
    judge_port: 3333
    client_id: "rm_client_receiver"
    qos: 1
    reconnect_period_sec: 2.0
    ros_prefix: "/judge"

judge_sender:
  ros__parameters:
    judge_host: "127.0.0.1"
    judge_port: 3333
    client_id: "rm_client_sender"
    qos: 1
    topic_cmd: "GuardCtrlCommand"
    reconnect_period_sec: 2.0
    ros_command_topic: "/semi_auto/command_id"

semi_auto_keyboard:
  ros__parameters:
    ros_command_topic: "/semi_auto/command_id"
    cooldown_ms: 1000
    rate_limit_ms: 1000